name: FacTrain
version: '${version}'
main: be.artex.factrain.Main
api-version: '1.19'
commands:
  bow:
    usage: "ยง4usage: /bow"
    description: "shows all custom bows"
    aliases:
      - bows
      - enderbow
  sword:
    usage: "ยง4usage: /sword"
    description: "shows all custom swords"
    aliases:
      - swords
      - assasinsword